/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DataConnection;
import Controller.ControllGetData;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class DonHangJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonHangJPanel
     */
    public DonHangJPanel() {
        initComponents();
      /*  JTableControll JTable=new JTableControll(jtb_dsdh);
        JTable.getData_HD(); */
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtf_ngay = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtf_hoten = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtb_ctdonhang = new javax.swing.JTable();
        jtf_tongtien = new javax.swing.JTextField();
        jtfma_kh = new javax.swing.JTextField();
        jtf_sdt = new javax.swing.JTextField();
        jtfma_dh = new javax.swing.JTextField();
        jbt_timkiem = new javax.swing.JButton();
        jbt_them = new javax.swing.JButton();
        jbt_xoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtf_dc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(628, 542));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("CHI TIẾT ĐƠN HÀNG");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Mã đơn hàng");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Ngày lập");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Tên khách hàng");

        jtf_hoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_hotenActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Mã khách hàng");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Số điện thoại");

        jtb_ctdonhang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtb_ctdonhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hàng", "Tên hàng", "Số lượng", "Giá"
            }
        ));
        jScrollPane3.setViewportView(jtb_ctdonhang);

        jtfma_kh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfma_khActionPerformed(evt);
            }
        });

        jbt_timkiem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbt_timkiem.setText("Tìm kiếm");
        jbt_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_timkiemActionPerformed(evt);
            }
        });

        jbt_them.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbt_them.setText("Thêm đơn hàng");
        jbt_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_themActionPerformed(evt);
            }
        });

        jbt_xoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbt_xoa.setText("Xóa đơn hàng");
        jbt_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_xoaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Địa chỉ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Tổng tiền");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 196, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfma_kh, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_dc, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfma_dh, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(jbt_timkiem)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbt_them)
                                .addGap(40, 40, 40)
                                .addComponent(jbt_xoa)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfma_dh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jbt_timkiem)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtf_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfma_kh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_sdt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_dc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_them)
                    .addComponent(jbt_xoa)
                    .addComponent(jtf_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_hotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_hotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_hotenActionPerformed

    private void jtfma_khActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfma_khActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfma_khActionPerformed

    private void jbt_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_timkiemActionPerformed
        // TODO add your handling code here:
        DataConnection con=new DataConnection();
        Connection c=con.getConnection();
        PreparedStatement pStmt=null,pStmt2=null;
        ResultSet rs1=null,rs2=null;
        try{
        pStmt=c.prepareStatement("select Ngay_Lap,Ho_Ten,dh.Ma_KH,So_DT_KH,Dia_Chi_KH from donhang dh join khachhang kh on dh.Ma_KH=kh.Ma_KH where Ma_DH=?;");
        pStmt.setString(1,(String)jtfma_dh.getText());
        rs1=pStmt.executeQuery();  
        rs1.next();
        jtf_ngay.setText(rs1.getString("Ngay_Lap")); 
        jtf_hoten.setText(rs1.getString("Ho_Ten"));
        jtfma_kh.setText(rs1.getString("Ma_KH"));
        jtf_sdt.setText(rs1.getString("So_DT_KH"));
        jtf_dc.setText(rs1.getString("Dia_Chi_KH")); 
        String [] arr={"Mã hàng hóa","Tên hàng hóa","Số lượng","Giá"};
        DefaultTableModel model=new DefaultTableModel(arr,0);
        pStmt2=c.prepareStatement("select ct.Ma_HH,Ten_HH,So_Luong,ct.Gia from chitietdonhang ct join hanghoa hh on ct.Ma_HH=hh.Ma_HH where Ma_DH=?");
        pStmt2.setString(1,jtfma_dh.getText());
        rs2=pStmt2.executeQuery();
        while(rs2.next()){
            Vector vector=new Vector();
            vector.add(rs2.getString("Ma_HH"));
            vector.add(rs2.getString("Ten_HH"));
            vector.add(rs2.getString("So_Luong"));
            vector.add(rs2.getString("Gia"));
            model.addRow(vector);
        }
        jtb_ctdonhang.setModel(model);
        CallableStatement cStmt=null;
        try{
        cStmt=c.prepareCall("{? = call TINHTIEN(?)}");
        cStmt.registerOutParameter(1, Types.INTEGER);
        cStmt.setString(2,(String)jtfma_dh.getText());
        cStmt.execute();
        int tongtien=cStmt.getInt(1);
        String s=String.valueOf(tongtien);
        jtf_tongtien.setText(s);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Lỗi!");
        }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Lỗi!");
            System.out.println("SQLException: " + ex.getMessage());
        }
        
    }//GEN-LAST:event_jbt_timkiemActionPerformed

    private void jbt_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_themActionPerformed
        // TODO add your handling code here:
        ThemDHJFrame DH=new ThemDHJFrame();
        DH.setVisible(true);
        DH.setResizable(false);
        DH.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jbt_themActionPerformed

    private void jbt_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_xoaActionPerformed
        // TODO add your handling code here:
     int n=JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn xóa đơn hàng này chứ?",null, JOptionPane.YES_NO_OPTION);
     if(n==JOptionPane.YES_OPTION){
        DataConnection con=new DataConnection();
        Connection c=con.getConnection();
        PreparedStatement pStmt=null;
        try{
        pStmt=c.prepareStatement("delete from donhang where Ma_DH=?");
        pStmt.setString(1,jtfma_dh.getText());
        pStmt.executeUpdate();
        
        }catch(SQLException ex){
             JOptionPane.showMessageDialog(null,"Lỗi!");
        }
        jtfma_dh.setText(null);
        jtf_ngay.setText(null);
        jtfma_kh.setText(null);
        jtf_hoten.setText(null);
        jtf_sdt.setText(null);
        jtf_dc.setText(null);
        jtf_tongtien.setText(null);
         DefaultTableModel model = (DefaultTableModel) jtb_ctdonhang.getModel();
         model.setRowCount(0);
     }
    }//GEN-LAST:event_jbt_xoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbt_them;
    private javax.swing.JButton jbt_timkiem;
    private javax.swing.JButton jbt_xoa;
    private javax.swing.JTable jtb_ctdonhang;
    private javax.swing.JTextField jtf_dc;
    private javax.swing.JTextField jtf_hoten;
    private javax.swing.JTextField jtf_ngay;
    private javax.swing.JTextField jtf_sdt;
    private javax.swing.JTextField jtf_tongtien;
    private javax.swing.JTextField jtfma_dh;
    private javax.swing.JTextField jtfma_kh;
    // End of variables declaration//GEN-END:variables
}
