/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DataConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class ThemDHJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ThemDHJFrame
     */
    public ThemDHJFrame() {
        initComponents();
        setTitle("Thêm đơn hàng");
        jtf_ngaylap.setText(String.valueOf(java.time.LocalDateTime.now()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_madh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtf_ngaylap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtf_makh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtf_hoten = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtf_dc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtf_sdt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_ctdh = new javax.swing.JTable();
        jtf_tongtien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtf_mahh = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtf_solg = new javax.swing.JTextField();
        jbt_them = new javax.swing.JButton();
        jbt_hoantat = new javax.swing.JButton();
        jbt_luu = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jbt_xoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("CHI TIẾT ĐƠN HÀNG");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Mã đơn hàng");

        jtf_madh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_madhActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Ngày lập");

        jtf_ngaylap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_ngaylapActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Mã khách hàng");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Họ tên");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Địa chỉ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Số điện thoại");

        jtb_ctdh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtb_ctdh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hàng hóa", "Tên hàng hóa", "Số lượng", "Giá"
            }
        ));
        jScrollPane1.setViewportView(jtb_ctdh);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Nhập mã hàng hóa");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Nhập số lượng");

        jbt_them.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbt_them.setText("Thêm");
        jbt_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_themActionPerformed(evt);
            }
        });

        jbt_hoantat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbt_hoantat.setText("Hoàn tất");
        jbt_hoantat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_hoantatActionPerformed(evt);
            }
        });

        jbt_luu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbt_luu.setText("Lưu");
        jbt_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_luuActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Tổng tiền");

        jbt_xoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbt_xoa.setText("Xóa");
        jbt_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_xoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_madh)
                                    .addComponent(jtf_ngaylap)
                                    .addComponent(jtf_makh)
                                    .addComponent(jtf_hoten)
                                    .addComponent(jtf_dc)
                                    .addComponent(jtf_sdt, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtf_mahh, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_solg, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbt_xoa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbt_them)))
                                .addGap(88, 88, 88)
                                .addComponent(jbt_hoantat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(jbt_luu)))
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_madh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_ngaylap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_makh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtf_dc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtf_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbt_hoantat)
                        .addComponent(jbt_luu)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtf_mahh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtf_solg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_them)
                    .addComponent(jbt_xoa))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_madhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_madhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_madhActionPerformed

    private void jtf_ngaylapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_ngaylapActionPerformed
        // TODO add your handling code here:
        jtf_ngaylap.setText(String.valueOf(java.time.LocalDateTime.now())); 
    }//GEN-LAST:event_jtf_ngaylapActionPerformed

    private void jbt_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_themActionPerformed
        // TODO add your handling code here:
        DataConnection con=new DataConnection();
        Connection c=con.getConnection();
        PreparedStatement pStmt=null;
        ResultSet rs=null;
        try{
            pStmt=c.prepareStatement("select Ten_HH,Gia from hanghoa where Ma_HH=?");
            pStmt.setString(1,jtf_mahh.getText());
            rs=pStmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jtb_ctdh.getModel();
            while(rs.next()){
                Vector vector=new Vector();
                vector.add(jtf_mahh.getText());
                vector.add(rs.getString("Ten_HH"));
                vector.add(jtf_solg.getText());
                vector.add(rs.getString("Gia"));
                model.addRow(vector);
            }
            jtf_mahh.setText(null);
            jtf_solg.setText(null);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Lỗi!");
        }
    }//GEN-LAST:event_jbt_themActionPerformed

    private void jbt_hoantatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_hoantatActionPerformed
        // TODO add your handling code here:
        DataConnection con=new DataConnection();
        Connection c=con.getConnection();
        PreparedStatement pStmt=null;
        ResultSet rs=null,rs2=null;
        try{
            pStmt=c.prepareStatement("select * from khachhang where Ma_KH=?");
            pStmt.setString(1,jtf_makh.getText());
            rs=pStmt.executeQuery();
            rs.next();
            jtf_hoten.setText(rs.getString("Ho_Ten"));
            jtf_dc.setText(rs.getString("Dia_Chi_KH"));
            jtf_sdt.setText(rs.getString("So_DT_KH"));
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Lỗi!");
        }
        int count=jtb_ctdh.getRowCount();
        int tong=0;
        for(int i=0;i<count;i++){
            tong=tong+(Integer.parseInt((String) jtb_ctdh.getValueAt(i,2)) * Integer.parseInt((String) jtb_ctdh.getValueAt(i,3)));
        }
        jtf_tongtien.setText(String.valueOf(tong));
    }//GEN-LAST:event_jbt_hoantatActionPerformed

    private void jbt_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_xoaActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) jtb_ctdh.getModel();
        int row=jtb_ctdh.getSelectedRow();
        if(row>-1){
            model.removeRow(row);
        }
        
    }//GEN-LAST:event_jbt_xoaActionPerformed

    private void jbt_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_luuActionPerformed
        // TODO add your handling code here:
        DataConnection con =new DataConnection();
        Connection c=con.getConnection();
        PreparedStatement pStmt=null;
        try{
            pStmt=c.prepareStatement("insert into donhang values(?,?,?)");
            pStmt.setString(1,jtf_madh.getText());
            pStmt.setString(2,jtf_makh.getText());
            pStmt.setString(3,jtf_ngaylap.getText());
            pStmt.executeUpdate();
            int a=jtb_ctdh.getRowCount();
            for(int i=0;i<a;i++){
               pStmt=null;
               try{
               pStmt=c.prepareStatement("insert into chitietdonhang values(?,?,?,?);");
               pStmt.setString(1,jtf_madh.getText());
               pStmt.setString(2, (String) jtb_ctdh.getValueAt(i,0));
               pStmt.setString(3, (String) jtb_ctdh.getValueAt(i,2));
               pStmt.setString(4, (String) jtb_ctdh.getValueAt(i,3));
               pStmt.executeUpdate();
               }catch(SQLException ex){
                   JOptionPane.showMessageDialog(null,"Lỗi!");
               }
            }
            JOptionPane.showMessageDialog(null,"Thành công!");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Lỗi!");
    }
    }//GEN-LAST:event_jbt_luuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemDHJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemDHJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemDHJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemDHJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemDHJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_hoantat;
    private javax.swing.JButton jbt_luu;
    private javax.swing.JButton jbt_them;
    private javax.swing.JButton jbt_xoa;
    private javax.swing.JTable jtb_ctdh;
    private javax.swing.JTextField jtf_dc;
    private javax.swing.JTextField jtf_hoten;
    private javax.swing.JTextField jtf_madh;
    private javax.swing.JTextField jtf_mahh;
    private javax.swing.JTextField jtf_makh;
    private javax.swing.JTextField jtf_ngaylap;
    private javax.swing.JTextField jtf_sdt;
    private javax.swing.JTextField jtf_solg;
    private javax.swing.JTextField jtf_tongtien;
    // End of variables declaration//GEN-END:variables
}
